### ISSUE TITLE
SQL syntax error when resetting a password.

### ISSUE THREAD

**Issue by damncabbage** [soupi/gathering#5]
The error:
```
ResultError (ServerError "42601" "syntax error at or near \"from\"" Nothing Nothing)
```

The URL (roughly):
https://gathering.purescript.org/reset-password/...bighashgoeshere.../my@email.address

The relevant query:
https://github.com/soupi/gathering/blame/master/src/Web/Gathering/Database.hs#L495-L497

What happens if you, umm, just drop the `\`s? 😅

**Comment by soupi** [comment]
First issue, exciting!

Thanks for reporting and sorry for the mess, I will take care of this today or tomorrow.

**Comment by soupi** [comment]
Fixed and deployed. Sorry about that!

**Comment by damncabbage** [comment]
No, not at all; thanks for writing+hosting this! 😅
